# Generated by Django 4.2.3 on 2023-10-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0002_subscriber_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="attachment",
            field=models.FileField(blank=True, upload_to="email_attachments/"),
        ),
    ]
