# Generated by Django 4.2.3 on 2023-10-28 12:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("emails", "0003_alter_email_attachment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="email",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
