# Generated by Django 4.2.3 on 2023-12-01 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompressImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_img", models.ImageField(upload_to="original_images/")),
                (
                    "quality",
                    models.IntegerField(
                        choices=[
                            (10, 10),
                            (20, 20),
                            (30, 30),
                            (40, 40),
                            (50, 50),
                            (60, 60),
                            (70, 70),
                            (80, 80),
                            (90, 90),
                            (100, 100),
                        ],
                        default=80,
                    ),
                ),
                ("compressed_img", models.ImageField(upload_to="compressed_images/")),
                ("compressed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
